---

name: Push (master)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

on:
  push:
    branches:
    - master

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
        chmod +x .github/scripts/create-github-release.sh
        .github/scripts/create-github-release.sh

  create_vscode_release:
    name: Create VSCode Release
    runs-on: ubuntu-latest
    needs: create_github_release
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: |
        npm install --global yarn
        yarn bootstrap-frozen
        yarn build
        yarn deploy -p $VSCE_TOKEN
