---

name: Push (master)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - master

jobs:
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: chmod +x .github/create-github-release
      - run: .github/create-github-release
  create_vscode_release:
    name: Create VSCode Release
    runs-on: ubuntu-latest
    needs: create_github_release
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: rm -rf node_modules
      - run: npm install --global yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn deploy
