---

name: Pull Request (master)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - master

jobs:
  check_package_version:
    name: Check Package Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: |
        chmod +x .github/scripts/check-package-version.sh
        .github/scripts/check-package-version.sh
